### ISSUE TITLE
Training with custom data

### ISSUE THREAD

**Issue by HamLaertes** [berlino/weaksp_em19#1]
Hi, I am curious about how can I use this code to train my data?
I downloaded the raw data you prepocessed on by the download link in the front page. But I found the data seemed different from the raw WikiTable dataset. Where can I get that preprocessing programs?
Thank u very much.

**Comment by berlino** [comment]
Step 2 is the one that searches for consistent programs; you can get the preprocessed data by Step 1 and 2, as mentioned in the readme.
